version: 2
updates:
  # Gradle (Java/Spring Boot) dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "/"
    reviewers:
      - "magwi"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "build(deps):"
      include: "scope"

  # GitHub Actions (CI/CD)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "/"
    reviewers:
      - "magwi"
    commit-message:
      prefix: "ci(deps):"
      include: "scope"